local ls = require 'luasnip'
local s = ls.snippet
local t = ls.text_node
local i = ls.insert_node

ls.add_snippets('cpp', {
  s('dsa_cpp', {
    t {
      '',
      '#include <bits/stdc++.h>',
      'using namespace std;',
      '',
      '#define int long long',
      '#define pb push_back',
      '#define mp make_pair',
      '#define ff first',
      '#define ss second',
      '#define all(x) (x).begin(), (x).end()',
      '#define sz(x) ((int)(x).size())',
      '#define rep(i, a, b) for (int i = a; i < b; i++)',
      '#define rrep(i, a, b) for (int i = a; i >= b; i--)',
      '#ifndef ONLINE_JUDGE',
      '#define debug(x)       \\',
      '    cerr << #x << " "; \\',
      '    _print(x);         \\',
      '    cerr << endl;',
      '#else',
      '#define debug(x)',
      '#endif',
      '#define fastio                        \\',
      '    ios_base::sync_with_stdio(false); \\',
      '    cin.tie(NULL);',
      '',
      '#undef int',
      'void _print(int t)',
      '{',
      '    cerr << t;',
      '}',
      '#define int long long',
      'void _print(string t)',
      '{',
      '    cerr << t;',
      '}',
      'void _print(char t)',
      '{',
      '    cerr << t;',
      '}',
      'void _print(double t)',
      '{',
      '    cerr << t;',
      '}',
      '',
      'template <class T, class V> void _print(pair<T, V> p);',
      'template <class T> void _print(vector<T> v);',
      'template <class T> void _print(set<T> v);',
      'template <class T, class V> void _print(map<T, V> v);',
      'template <class T, class V> void _print(pair<T, V> p)',
      '{',
      '    cerr << "{";',
      '    _print(p.ff);',
      '    cerr << ",";',
      '    _print(p.ss);',
      '    cerr << "}";',
      '}',
      'template <class T> void _print(vector<T> v)',
      '{',
      '    cerr << "[ ";',
      '    for (T i : v) {',
      '        _print(i);',
      '        cerr << " ";',
      '    }',
      '    cerr << "]";',
      '}',
      'template <class T> void _print(set<T> v)',
      '{',
      '    cerr << "[ ";',
      '    for (T i : v) {',
      '        _print(i);',
      '        cerr << " ";',
      '    }',
      '    cerr << "]";',
      '}',
      'template <class T, class V> void _print(map<T, V> v)',
      '{',
      '    cerr << "[ ";',
      '    for (auto i : v) {',
      '        _print(i);',
      '        cerr << " ";',
      '    }',
      '    cerr << "]";',
      '}',
      '',
      'void fio()',
      '{',
      '#ifndef ONLINE_JUDGE',
      '    {',
      '        ifstream in("/home/rpeb/CLionProjects/DSA/input.txt");',
      '        ofstream out("/tmp/_dsa_input_stripped.txt");',
      '        string line;',
      '        while (getline(in, line)) {',
      '            line.erase(remove(line.begin(), line.end(), \'"\'), line.end());',
      '            out << line << "\\n";',
      '        }',
      '    }',
      '    if (freopen("/tmp/_dsa_input_stripped.txt", "r", stdin) == nullptr) {',
      '        cerr << "Error opening input.txt" << endl;',
      '    }',
      '    if (freopen("/home/rpeb/CLionProjects/DSA/output.txt", "w", stdout) == nullptr) {',
      '        cerr << "Error opening output.txt" << endl;',
      '    }',
      '#endif',
      '}',
      '',
      'void solve()',
      '{',
    },
    i(1, '    '),
    t {
      '}',
      '',
      '',
      '',
      'int32_t main()',
      '{',
      '    fastio fio();',
      '    int t;',
      '    cin >> t;',
      '    while (t--)',
      '        solve();',
      '    return 0;',
      '}',
      '',
    },
  }),
  s('fio', {
    t {
      '#ifndef ONLINE_JUDGE',
      '    if (freopen("/home/rpeb/CLionProjects/CP_Workspace/input.txt", "r", stdin) == nullptr) {',
      '        cerr << "Error opening input.txt" << endl;',
      '    }',
      '    if (freopen("/home/rpeb/CLionProjects/CP_Workspace/output.txt", "w", stdout) == nullptr) {',
      '        cerr << "Error opening output.txt" << endl;',
      '    }',
      '#endif',
    },
  }),
  s('fio_dsa', {
    t {
      '#ifndef ONLINE_JUDGE',
      '    if (freopen("/home/rpeb/CLionProjects/DSA/input.txt", "r", stdin) == nullptr) {',
      '        cerr << "Error opening input.txt" << endl;',
      '    }',
      '    if (freopen("/home/rpeb/CLionProjects/DSA/output.txt", "w", stdout) == nullptr) {',
      '        cerr << "Error opening output.txt" << endl;',
      '    }',
      '#endif',
    },
  }),
  s('split', {
    t {
      'vector<string> split(const string &s, char sep) {',
      '    vector<string> result;',
      '    for (auto part : s | views::split(sep)) {',
      '        result.emplace_back(string(part.begin(), part.end()));',
      '    }',
      '    return result;',
      '}',
    },
  }),
})
